# Kết nối DB
spring.datasource.url=jdbc:postgresql://localhost:5432/RebikeDatabase
spring.datasource.username=Houz123
spring.datasource.password=Rebike123!

# Cấu hình JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
